name: ${artifactId}
main: ${main}
author: ${author}
version: ${version}
description: ${description}
website: ${website}
softdepend: [ IslandMines, PlaceholderAPI, ShopGUIPlus, Vault, WorldEdit, WorldGuard ]
commands:
  enchanter:
    description: Main Command - PickaxeUpgrades
    aliases: [ xenchanter, ce ]
  energy:
    description: Energy Command - PickaxeUpgrades
    aliases: [ xenergy ]
  upgrade:
    description: Upgrade your Pickaxe - PickaxeUpgrades
    aliases: [ xupgrade, upgradepickaxe, upgradepick, upgrades ]